### ISSUE TITLE
Add A daily shop

### ISSUE THREAD

**Issue by SaiOwO** [geode-sdk/indexer#1136]
### Your mod link

https://github.com/SaiOwO/A-Dailty-Shop/releases/download/r/elsai.a_daily_shop.geode

### Your mod source code

https://github.com/SaiOwO/A-Dailty-Shop

### Your mod description

Adds a new item shop

**Comment by Cvolton** [comment]
would be nice to have some sort of disclaimer that the icons stay unlocked even if you remove the mod at least, since some people might not expect that

 (or even better a way to revert the purchases before/while uninstalling, you might already consider this cheating in the context of the mod though, so idk if this is needed)

other than that, nice mod

**Comment by Cvolton** [comment]
!accept
