### ISSUE TITLE
MainLevelsEditor v3

### ISSUE THREAD

**Issue by user95401** [geode-sdk/indexer#1231]
### Your mod link

https://github.com/user95401/MainLevelsEditor/releases/download/v3/user95401.mainlevelseditor.geode

### Your mod source code

https://github.com/user95401/MainLevelsEditor

### Your mod description

u can edit:
- main levels setup (stars, song, name, difficulty)
- level pages count
- bg color for page
- songs

and "Load Failed!" bypass here

summary u can add ur own level in level select layer

**Comment by user95401** [comment]
why the fuck its wait accept so looong

**Comment by Cvolton** [comment]
can you use the geode provided config directory instead of directly polluting resources? you don't necessarily have to use geode utils to interface with the files, but please at least save your files in the proper locations. You can add a cocos search path if you need the game to treat stuff inside it as if it were in the resources folder

**Comment by user95401** [comment]
# 😑

**Comment by user95401** [comment]
configuration design is specially made so that the process of configuring levels be in exactly one folder (levels). It's comfortable and necessary that is :D

**Comment by user95401** [comment]
what if i do deletion folders on mod uninstall?
must i?
