### ISSUE TITLE
Add ProfileBio

### ISSUE THREAD

**Issue by YellowCat98** [geode-sdk/indexer#1801]
### Your mod link

https://github.com/YellowCat98/ProfileBio/releases/download/1.0.0/yellowcat98.profilebio.geode

### Your mod source code

https://github.com/YellowCat98/ProfileBio

### Your mod description

allows you to add a bio to your geometry dash profile.

**Comment by Cvolton** [comment]
i feel like this is kinda on the edge of what we should allow - not because of the idea but because of the implementation - the experience could be much more seamless and it feels like there hasn't been much thought put into it

that being said, it's good enough to be accepted

also any nodes added in `loadPageFromUserInfo` should also be added to `m_buttons`, so it doesn't get duplicated on refresh. considering how small the mod is, i could already request a change for this, but you're kinda saved by the z order not making it obvious that this happens to the end user, so it's only really an annoyance that shows up in devtools

**Comment by Cvolton** [comment]
!accept
