### ISSUE TITLE
Add Level History v1.0.1

### ISSUE THREAD

**Issue by SergeyMC9730** [geode-sdk/indexer#1878]
### Your mod link

https://github.com/SergeyMC9730/levelhistory/releases/download/v1.0.1/dogotrigger.level_history.geode

### Your mod source code

https://github.com/SergeyMC9730/levelhistory

### Your mod description

Look through and play deleted and outdated levels using GDHistory or other sources

**Comment by OM3GA6400** [comment]
you should make is so you can copy the levels

**Comment by SergeyMC9730** [comment]
:/

**Comment by OM3GA6400** [comment]
> :/

bro the mods hate you

**Comment by Cvolton** [comment]
in gdhistory provider:

found a typo
```
PARSE_INT(level->m_ratings, leveljson["raiting"]);
PARSE_INT(level->m_ratingsSum, leveljson["raiting_sum"]);
```

feature score is level->m_featured, m_rateFeature is whether the level was sent for feature (which is not exposed by gdhistory, even though the db has the value logged for a few levels)

---

also while adding the button to other-filter-menu, you should just call updateLayout on it and let the layout handle the positioning, otherwise it will overlap with loquibot and other mods that use this menu

**Comment by Cvolton** [comment]
also the loading circle doesnt disappear for me sometimes and the non-functional get it button is kinda weird

also ive just noticed that the code already more or less emulates the layout behavior and the other things arent blocking issues per se, so im accepting but it would be nice to see them resolved

**Comment by Cvolton** [comment]
!accept
