### ISSUE TITLE
Add TheSillyDoggo.QOLMod

### ISSUE THREAD

**Issue by TheSillyDoggo** [geode-sdk/indexer#475]
### Your mod link

https://github.com/TheSillyDoggo/QOLMod/releases/download/v1.0.0/TheSillyDoggo.Cheats.geode

**Comment by TheSillyDoggo** [comment]
i didn't really want to make it open source but i can add you to the repo to see  it

**Comment by TheSillyDoggo** [comment]
i added you to it you can see it https://github.com/TheSillyDoggo/GeodeMenu

**Comment by HJfod** [comment]
Wtf we permit uppercase letters in IDs now? Well ig that's not your fault, the mod code looks to be fine aside from this, which will break if NodeIDs ever adds IDs to these scenes (the default ID for a layer is the layer name, so `PauseLayer` and `PlayLayer` in this case). Tbh you should probably either use `typeinfo_cast` or make a PR in NodeIDs that add just the layer names, so the mod stays future-compatible. Otherwise can't see any other compatability issues and the actual mod itself looks really good!
![image](https://github.com/geode-sdk/indexer/assets/60038575/15b153e3-867f-4d72-9c7b-5732552233a9)

**Comment by TheSillyDoggo** [comment]
yeah that was just to fix the button not being clickable on the pause menu, and i didn't know i wasn't allowed capitals in mod ids

**Comment by TheSillyDoggo** [comment]
do i have to do the node ids compatibility right now or can it be accepted and i do it tomorrow

**Comment by HJfod** [comment]
ye that's fine 👍

**Comment by HJfod** [comment]
!accept
